title: Helyreigazítások
email: hngrhorace@gmail.com
description: >
 Helyreigazítások a magyar internetről.
baseurl: ""
url: "https://helyreigazitasok.hu"
paginate: 7
paginate_path: "/pages/:num/"
emptyArray: []
exclude: ["README.md", "Gemfile.lock", "Gemfile", "LICENSE", "CNAME", "staticman.yml"]
permalink: /:categories/:year/:month/:day/:title
collections:
  magyar-idok:
    output: true
  index-hu: 
    output: true
  origo: 
    output: true
  hvg: 
    output: true
  huszonnegy:
    output: true
  nyolcnyolcnyolc:
    output: true
  negynegynegy:
    output: true
  pesti-sracok:
    output: true
defaults:
  - scope:
      path: ""
      type: index-hu
    values:
      layout: correction
      origin: "Index"
      originOn: "az Indexen"
      originFrom: "az Indexről"
  - scope:
      path: ""
      type: magyar-idok
    values:
      layout: correction
      origin: "Magyar Idők"
      originOn: "a Magyar Időkben"
      originFrom: "a Magyar Időkből"
  - scope:
      path: ""
      type: origo
    values:
      layout: correction
      origin: "Origó"
      originOn: "az Origón"
      originFrom: "az Origóról"
  - scope:
      path: ""
      type: hvg
    values:
      layout: correction
      origin: "HVG"
      originOn: "a HVG-ben"
      originFrom: "a HVG-ből"
  - scope:
      path: ""
      type: huszonnegy
    values:
      layout: correction
      origin: "24.hu"
      originOn: "a 24.hu-n"
      originFrom: "a 24.hu-ról"
  - scope:
      path: ""
      type: nyolcnyolcnyolc
    values:
      layout: correction
      origin: "888"
      originOn: "a 888-on"
      originFrom: "a 888-ról"
  - scope:
      path: ""
      type: negynegynegy
    values:
      layout: correction
      origin: "444"
      originOn: "a 444-en"
      originFrom: "a 444-ről"
  - scope:
      path: ""
      type: pesti-sracok
    values:
      layout: correction
      origin: "Pesti Srácok"
      originOn: "a Pesti Srácokon"
      originFrom: "a Pesti Srácoktól"

