title: Helyreigazítások
email: hngrhorace@gmail.com
description: >
 Helyreigazítások a magyar internetről.
baseurl: ""
url: "https://helyreigazitasok.hu"
paginate: 7
paginate_path: "/pages/:num/"
exclude: ["README.md", "Gemfile.lock", "Gemfile", "LICENSE", "CNAME"]
permalink: /:categories/:year/:month/:day/:title
collections:
  magyar-idok:
    output: true
  index-hu: 
    output: true
  origo: 
    output: true
defaults:
  - scope:
      path: ""
      type: index-hu
    values:
      layout: correction
      origin: "az Indexen"
  - scope:
      path: ""
      type: magyar-idok
    values:
      layout: correction
      origin: "a Magyar Időkben"
  - scope:
      path: ""
      type: origo
    values:
      layout: correction
      origin: "az Origón"

